In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import selenium
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import time
from webdriver_manager.chrome import ChromeDriverManager
import re

In [15]:
driver = webdriver.Chrome('chromedriver.exe')
time.sleep(2)

url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)
driver.maximize_window()

In [33]:
rank = []

try:
    videorank = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for ranks in videorank:
        rank.append(ranks.text)
except NoSuchElementException:
    rank.append('No details available')
except StaleElementReferenceException:
    rank.append('No details available')
    
name = []
    
try:
    videonames = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for video in videonames:
        name.append(video.text)
except NoSuchElementException:
    name.append('No details available')
except StaleElementReferenceException:
    name.append('No details available')   

uploader = []
    
try:
    upload = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for upldr in upload:
        uploader.append(upldr.text)
except NoSuchElementException:
    uploader.append('No details available')
except StaleElementReferenceException:
    uploader.append('No details available')    
    
views = []
    
try:
    videoviews = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for vv in videoviews:
        views.append(vv.text)
except NoSuchElementException:
    views.append('No details available')
except StaleElementReferenceException:
    views.append('No details available')     

date = []
    
try:
    uploaddate = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for updd in uploaddate:
        date.append(updd.text)
except NoSuchElementException:
    date.append('No details available')
except StaleElementReferenceException:
    date.append('No details available')     



namelist = pd.DataFrame()
namelist['Video Rank'] = rank
namelist['Video Name'] = name
namelist['Artist'] = uploader
namelist['Upload Date'] = date
namelist['Video Views'] = views
namelist

,Video Rank,Video Name,Artist,Upload Date,Video Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.25
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.76
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.20
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.63
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.43
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.03
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[21]",Miroshka TV,"February 27, 2018",4.56
7,8.,"""Phonics Song with Two Words""[22]",ChuChu TV,"March 6, 2014",4.49
8,9.,"""Masha and the Bear – Recipe for Disaster""[23]",Get Movies,"January 31, 2012",4.49
9,10.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.47
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.35
11,12.,"""Dame Tu Cosita""[30]",El Chombo,"April 5, 2018",3.87
12,13.,"""Wheels on the Bus""[31]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.72
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.65
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.53
15,16.,"""Sorry""[34]",Justin Bieber,"October 22, 2015",3.52
16,17.,"""Counting Stars""[35]",OneRepublic,"May 31, 2013",3.52
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.41
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.24
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.24
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.24
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.23
22,23.,"""Let Her Go""[41]",Passenger,"July 25, 2012",3.18
23,24.,"""Bailando""[42]",Enrique Iglesias,"April 11, 2014",3.17
24,25.,"""Lean On""[43]",Major Lazer,"March 22, 2015",3.17
25,26.,"""Shake It Off""[44]",Taylor Swift,"August 18, 2014",3.15
26,27.,"""Baa Baa Black Sheep""[45]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.14
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.10
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.07
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.05

In [100]:
import time

driver = webdriver.Chrome('chromedriver.exe')
time.sleep(2)

url = "https://www.bcci.tv/"
driver.get(url)
driver.maximize_window()
time.sleep(2)

intmatch = driver.find_element_by_xpath("//li[@class='nav-item ml-0']")
intmatch.click()
time.sleep(2)


series = []

seriesdriver = driver.find_elements_by_xpath("//span[@class='ng-binding']")

for ser in seriesdriver:
    series.append(ser.text)
series

matchtime = []

matchtimedriver = driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")

for time in matchtimedriver:
    matchtime.append(time.text)
matchtime


matchdate = []

matchdatedriver = driver.find_elements_by_xpath("//h5[@class='ng-binding']")

for date in matchdatedriver:
    matchdate.append(date.text)
matchdate

matchvenue = []

matchvenuedriver = driver.find_elements_by_xpath("//span[@class='ng-binding ng-scope']")

for venue in matchvenuedriver:
    matchvenue.append(venue.text)
matchvenue

urls = []

urldriver = driver.find_elements_by_xpath("//div[@class='fixture-card-bottom']/a")

for link in urldriver:
    urls.append(link.get_attribute('href'))
urls

import time
match = []

for link in urls:                 
    driver.get(link)
    time.sleep(2)
    
    try:                    
        matchtitle =driver.find_element_by_xpath("/html/body/div[3]/div/div[1]/div[3]/div[6]/div[4]/div[2]/div[2]/div/div/ul/li[2]/span[2]")
        match.append(matchtitle.text)
    except NoSuchElementException:
        match.append('No details available')
        
match

['India VS Sri Lanka',
 'Pakistan Women VS India Women',
 'New Zealand Women VS India Women',
 'West Indies Women VS India Women',
 'India VS Sri Lanka',
 'England Women VS India Women',
 'India Women VS Australia Women',
 'India Women VS Bangladesh Women']

In [101]:
matchlist = pd.DataFrame()
matchlist['Series Name'] = series
matchlist['Match'] = match
matchlist['Match Date'] = matchdate
matchlist['Match Time'] = matchtime
matchlist['Venue'] = matchvenue
matchlist

#No match format available on the details page.

,Series Name,Match,Match Date,Match Time,Venue
0,SRI LANKA TOUR OF INDIA TEST SERIES 2022,India VS Sri Lanka,4 MAR 2022,9:30 AM IST,"Punjab Cricket Association IS Bindra Stadium,"
1,ICC WOMENS WORLD CUP 2022,Pakistan Women VS India Women,6 MAR 2022,6:30 AM IST,"Bay Oval,"
2,ICC WOMENS WORLD CUP 2022,New Zealand Women VS India Women,10 MAR 2022,6:30 AM IST,"Seddon Park,"
3,ICC WOMENS WORLD CUP 2022,West Indies Women VS India Women,12 MAR 2022,6:30 AM IST,"Seddon Park,"
4,SRI LANKA TOUR OF INDIA TEST SERIES 2022,India VS Sri Lanka,12 MAR 2022,2:30 PM IST,"M Chinnaswamy Stadium,"
5,ICC WOMENS WORLD CUP 2022,England Women VS India Women,16 MAR 2022,6:30 AM IST,"Bay Oval,"
6,ICC WOMENS WORLD CUP 2022,India Women VS Australia Women,19 MAR 2022,6:30 AM IST,"Eden Park,"
7,ICC WOMENS WORLD CUP 2022,India Women VS Bangladesh Women,22 MAR 2022,6:30 AM IST,"Seddon Park,"

In [214]:
import time

driver = webdriver.Chrome('chromedriver.exe')
time.sleep(2)

url = "https://www.statisticstimes.com/"
driver.get(url)
driver.maximize_window()
time.sleep(2)

economybtn = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
economybtn.click()

time.sleep(2)

indiabtn = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
indiabtn.click()
time.sleep(2)

In [217]:
indstatesbtn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
indstatesbtn.click()
time.sleep(2)

In [225]:
gdprank = []

try:
    gdprankdriver = driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]")
    for rank in gdprankdriver:
        gdprank.append(rank.text)
except NoSuchElementException:
    gdprank.append('No details available')
except StaleElementReferenceException:
    gdprank.append('No details available')

gdprank

gdpstate = []

try:
    gdpstatedriver = driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]")
    for state in gdpstatedriver:
        gdpstate.append(state.text)
except NoSuchElementException:
    gdpstate.append('No details available')
except StaleElementReferenceException:
    gdpstate.append('No details available')

gdpstate

gsdp1920 = []

try:
    gsdp1920driver = driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]")
    for gsdp1 in gsdp1920driver:
        gsdp1920.append(gsdp1.text)
except NoSuchElementException:
    gsdp1920.append('No details available')
except StaleElementReferenceException:
    gsdp1920.append('No details available')

gsdp1920

gsdp1819 = []

try:
    gsdp1819driver = driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]")
    for gsdp2 in gsdp1819driver:
        gsdp1819.append(gsdp2.text)
except NoSuchElementException:
    gsdp1819.append('No details available')
except StaleElementReferenceException:
    gsdp1819.append('No details available')

gsdp1819


gsdpshare = []

try:
    gsdpsharedriver = driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]")
    for share in gsdpsharedriver:
        gsdpshare.append(share.text)
except NoSuchElementException:
    gsdpshare.append('No details available')
except StaleElementReferenceException:
    gsdpshare.append('No details available')

gsdpshare

gdp1 = []

try:
    gdp1driver = driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]")
    for gdp in gdp1driver:
        gdp1.append(gdp.text)
except NoSuchElementException:
    gdp1.append('No details available')
except StaleElementReferenceException:
    gdp1.append('No details available')

gsdpshare



indiagdplist = pd.DataFrame()
indiagdplist['Rank'] = gdprank
indiagdplist['State'] = gdpstate
indiagdplist['GSDP (19-20)'] = gsdp1920
indiagdplist['GSDP (18-19)'] = gsdp1819
indiagdplist['GSDP Share'] = gsdpshare
indiagdplist['GDP in Millions'] = gdp1
indiagdplist.head(33)

,Rank,State,GSDP (19-20),GSDP (18-19),GSDP Share,GDP in Millions
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [274]:
import time

driver = webdriver.Chrome('chromedriver.exe')
time.sleep(2)

url = "https://github.com/"
driver.get(url)
driver.maximize_window()
time.sleep(2)

explorebtn = driver.find_element_by_xpath("//details[@class='HeaderMenu-details details-overlay details-reset width-full']")
explorebtn.click()

time.sleep(1)

trendingbtn = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
try:
    trendingbtn.click()
except:
    driver.get(trendingbtn.get_attribute('href'))
time.sleep(2)

repositorname = []

try:
    repnamedriver = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for name in repnamedriver:
        repositorname.append(name.text)
except NoSuchElementException:
    repositorname.append('No details available')
except StaleElementReferenceException:
    repositorname.append('No details available')

repositorname

urls = []

urldriver = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

for link in urldriver:
    urls.append(link.get_attribute('href'))
urls

time.sleep(2)

contributors = []
replanguage = []
repdesc = []

for link in urls:                 
    driver.get(link)
    time.sleep(2)
    
    try:                    
        cont =driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        contributors.append(cont.text)
    except NoSuchElementException:
        contributors.append('No details available')
        
    try:                    
        replang =driver.find_element_by_xpath("//li[@class='d-inline']//a//span")
        replanguage.append(replang.text)
    except NoSuchElementException:
        replanguage.append('No details available')
        
    try:                    
        rdesc =driver.find_element_by_xpath("//p[@class='f4 my-3']")
        repdesc.append(rdesc.text)
    except NoSuchElementException:
        repdesc.append('No details available')
        
repdesc


githublist = pd.DataFrame()
githublist['Repo Name'] = repositorname
githublist['Repo Desc'] = repdesc
githublist['Repo Lang'] = replanguage
githublist['Repo Contributors'] = contributors
githublist['URL'] = urls
githublist

,Repo Name,Repo Desc,Repo Lang,Repo Contributors,URL
0,almerico / bombardier,bombardier,HCL,9,https://github.com/almerico/bombardier
1,iaddis / metalnes,Transistor level NES simulation,JavaScript,No details available,https://github.com/iaddis/metalnes
2,AppFlowy-IO / AppFlowy,AppFlowy is an open-source alternative to Noti...,Rust,42,https://github.com/AppFlowy-IO/AppFlowy
3,cat-milk / Anime-Girls-Holding-Programming-Books,Anime Girls Holding Programming Books,No details available,181,https://github.com/cat-milk/Anime-Girls-Holdin...
4,HashLips / hashlips_art_engine,HashLips Art Engine is a tool used to create m...,JavaScript,12,https://github.com/HashLips/hashlips_art_engine
5,freqtrade / freqtrade,"Free, open source crypto trading bot",Python,203,https://github.com/freqtrade/freqtrade
6,erkexzcx / stoppropaganda,DOS application to stop pro-Russian aggression...,Go,10,https://github.com/erkexzcx/stoppropaganda
7,AlexTrushkovsky / NoWarDDoS,DDoS Russian websites to help Ukraine to win t...,Python,10,https://github.com/AlexTrushkovsky/NoWarDDoS
8,MHProDev / MHDDoS,"Best DDoS Attack Script Python3, Cyber Attack ...",Python,3,https://github.com/MHProDev/MHDDoS
9,ajax-lives / NoRussian,Volunteer DoS tool via HTML + JS,HTML,10,https://github.com/ajax-lives/NoRussian
10,Developer-Y / cs-video-courses,List of Computer Science courses with video le...,No details available,60,https://github.com/Developer-Y/cs-video-courses
11,palahsu / DDoS-Ripper,DDos Ripper a Distributable Denied-of-Service ...,Python,No details available,https://github.com/palahsu/DDoS-Ripper
12,curated-intel / Ukraine-Cyber-Operations,Curated Intelligence is working with analysts ...,No details available,8,https://github.com/curated-intel/Ukraine-Cyber...
13,techchipnet / CamPhish,Grab cam shots from target's phone front camer...,HTML,2,https://github.com/techchipnet/CamPhish
14,ytdl-org / youtube-dl,Command-line program to download videos from Y...,Python,768,https://github.com/ytdl-org/youtube-dl
15,github / advisory-database,Security vulnerability database inclusive of C...,No details available,3,https://github.com/github/advisory-database
16,cyprosecurity / API-SecurityEmpire,API Security Projecto aims to present unique a...,No details available,2,https://github.com/cyprosecurity/API-SecurityE...
17,LimerBoy / Impulse,💣 Impulse Denial-of-service ToolKit,Python,7,https://github.com/LimerBoy/Impulse
18,RunaCapital / awesome-oss-alternatives,Awesome list of open-source startup alternativ...,Python,31,https://github.com/RunaCapital/awesome-oss-alt...
19,jseidl / GoldenEye,GoldenEye Layer 7 (KeepAlive+NoCache) DoS Test...,Python,5,https://github.com/jseidl/GoldenEye
20,Luzhnuy / attacker,No details available,Python,2,https://github.com/Luzhnuy/attacker
21,hwdsl2 / setup-ipsec-vpn,"Scripts to build your own IPsec VPN server, wi...",Shell,15,https://github.com/hwdsl2/setup-ipsec-vpn
22,vinta / awesome-python,"A curated list of awesome Python frameworks, l...",Python,393,https://github.com/vinta/awesome-python
23,uberhalit / EldenRingFpsUnlockAndMore,"A small utility to remove frame rate limit, ch...",C#,3,https://github.com/uberhalit/EldenRingFpsUnloc...
24,sindresorhus / awesome,😎 Awesome lists about all kinds of interesting...,No details available,518,https://github.com/sindresorhus/awesome

In [293]:
import time

driver = webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
time.sleep(2)

url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)

hot100btn = driver.find_element_by_xpath("//*[@id='main-wrapper']/header/div[2]/div/nav/ul/li[1]/a")
hot100btn.click()

time.sleep(5)

In [390]:
songname = []

try:
    songnamedriver= driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li/h3")
    for name in songnamedriver:
        songname.append(name.text.strip(""))
except NoSuchElementException:
    songname.append('No details available')

songname

artistname = []

try:
    artistnamedriver= driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li[1]/span")
    for aname in artistnamedriver:
        artistname.append(aname.text)
except NoSuchElementException:
    artistname.append('No details available')

artistname


lastweekrank = []

try:
    lastweekrankdriver= driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li[4]")
    for lweek in lastweekrankdriver:
        lastweekrank.append(lweek.text)
except NoSuchElementException:
    lastweekrank.append('No details available')

lastweekrank

peakposrank = []

try:
    peakposrankdriver= driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li[5]")
    for pprank in peakposrankdriver:
        peakposrank.append(pprank.text)
except NoSuchElementException:
    peakposrank.append('No details available')

peakposrank


weaksonchart = []

try:
    weaksonchartdriver= driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li[6]")
    for wkoncrt in weaksonchartdriver:
        weaksonchart.append(wkoncrt.text)
except NoSuchElementException:
    weaksonchart.append('No details available')

weaksonchart

billboardlist = pd.DataFrame()
billboardlist['Song Name'] = songname
billboardlist['Artist'] = artistname
billboardlist['Last Week'] = lastweekrank
billboardlist['Peak POS'] = peakposrank
billboardlist['Weeks on Chart'] = weaksonchart
billboardlist.head(10)

,Song Name,Artist,Last Week,Peak POS,Weeks on Chart
0,We Don't Talk About Bruno,"Carolina Gaitan, Mauro Castillo, Adassa, Rhenz...",1,1,8
1,Heat Waves,Glass Animals,4,2,57
2,Easy On Me,Adele,3,1,19
3,abcdefu,GAYLE,7,4,13
4,Stay,The Kid LAROI & Justin Bieber,5,1,32
5,Super Gremlin,Kodak Black,6,5,15
6,Shivers,Ed Sheeran,8,4,23
7,Ghost,Justin Bieber,9,8,21
8,Thats What I Want,Lil Nas X,12,9,22
9,Pushin P,Gunna & Future Featuring Young Thug,11,7,6

In [392]:
import time

driver = webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
time.sleep(2)

url = "https://www.naukri.com/"
driver.get(url)
time.sleep(2)

userinput = input('Enter the Search Keyword: ')

time.sleep(2)

search = driver.find_element_by_class_name("suggestor-input")
search
time.sleep(2)

search.send_keys(userinput)
time.sleep(2)

searchbtn = driver.find_element_by_xpath("//div[@class='qsbSubmit']")
searchbtn
searchbtn.click()

Enter the Search Keyword: Data science

In [408]:
jobname = []

try:
    jobnamedriver = driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
    for name in jobnamedriver:
        jobname.append(name.text)
except NoSuchElementException:
    jobname.append('No details available')

jobname

companyname = []

try:
    companynamedriver = driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
    for cname in companynamedriver:
        companyname.append(cname.text)
except NoSuchElementException:
    companyname.append('No details available')

companyname

keyskills = []

try:
    keyskillsdriver = driver.find_elements_by_xpath("//ul[@class='tags has-description']")
    for kskills in keyskillsdriver:
        keyskills.append(kskills.text.replace('\n', ", "))
except NoSuchElementException:
    keyskills.append('No details available')

keyskills


joblocation = []

try:
    joblocationdriver = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")
    for jlocation in joblocationdriver:
        joblocation.append(jlocation.text.replace('\n', ", "))
except NoSuchElementException:
    joblocation.append('No details available')

joblocation

urls = []

urldriver = driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for link in urldriver:
        urls.append(link.get_attribute("href"))
urls

jobrole = []

for link in urls:                 
    driver.get(link)
    time.sleep(2)
    
    try:                    
        role =driver.find_element_by_xpath("//div[@class='details']/span")
        jobrole.append(role.text)
    except NoSuchElementException:
        jobrole.append('No details available')
        
jobrole

['Data Analyst',
 'Data Scientist',
 'Analytics Consultant',
 'Data Engineer',
 'Business Analyst',
 'No details available',
 'Business Analyst',
 'Data Analyst',
 'No details available',
 'Manager - Machine Learning',
 'No details available',
 'Business Analyst',
 'No details available',
 'Head - Analytics / BI',
 'Business Analyst',
 'Data Analyst',
 'No details available',
 'Analytics Consultant',
 'Business Analyst',
 'Business Analyst']

In [410]:
naukrijoblist = pd.DataFrame()
naukrijoblist ['Job Name'] = jobname
naukrijoblist ['Designation'] = jobrole
naukrijoblist ['Company'] = companyname
naukrijoblist ['Skills they hire for'] = keyskills
naukrijoblist ['Location'] = joblocation
naukrijoblist ['Job Link'] = urls
naukrijoblist

,Job Name,Designation,Company,Skills they hire for,Location,Job Link
0,Job | Business Analyst | RPA (Uipath) II HCL T...,Data Analyst,HCL,"verbal, RPA, ABBYY, written communication, Vis...","Noida, Mumbai, Hyderabad/Secunderabad, Pune, C...",https://www.naukri.com/job-listings-business-a...
1,Opening with Data Science,Data Scientist,PwC,"Data Science, Big Data, Python, Hadoop, R, Hiv...","Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",https://www.naukri.com/job-listings-opening-wi...
2,Product Owner - Data Engineering,Analytics Consultant,GENPACT INDIA PRIVATE LIMITED,"IT Skills, Data Science, Machine Learning, Clo...","Noida, Mumbai, Hyderabad/Secunderabad, Pune, G...",https://www.naukri.com/job-listings-product-ow...
3,Hiring For Big Data Engineer,Data Engineer,PwC,"python, Hadoop, Spark, HDFS, Cassandra, Hive, ...","Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",https://www.naukri.com/job-listings-hiring-for...
4,Business Analyst - Automation,Business Analyst,Jacobs,"RPA, Business Analyst, Business Modeling, Agil...","Kolkata, Mumbai, Hyderabad/Secunderabad, Gurga...",https://www.naukri.com/job-listings-business-a...
5,Assistant Manager/Manager- Data Scientist,No details available,Genpact,"Data Science, python, predictive modeling, Art...","Gurgaon/Gurugram, Bangalore/Bengaluru",https://www.naukri.com/job-listings-assistant-...
6,Urgent Hiring - Maritime Logistics Research,Business Analyst,Evalueserve,"logistics, maritime, Market Research","Kolkata, Pune, Chennai, Bangalore/Bengaluru, D...",https://www.naukri.com/job-listings-urgent-hir...
7,SAS Fraud Analyst,Data Analyst,Lericon Informatics Pvt. Ltd.,"Social Network Analysis, SAS Financial Crime M...","Mumbai, Hyderabad/Secunderabad, Pune, Chennai,...",https://www.naukri.com/job-listings-sas-fraud-...
8,Technical Project Manager,No details available,Birlasoft,"IT Skills, Project Management, Azure, BPO, pro...","Noida, Mumbai, Chandigarh, Nagpur, Hyderabad/S...",https://www.naukri.com/job-listings-technical-...
9,Machine Learning Ops,Manager - Machine Learning,Mindtree,"Data Science, Machine Learning, Java, Ansible,...","Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",https://www.naukri.com/job-listings-machine-le...
10,MSBI + Cosmos Developer- Urgent Hiring,No details available,Capgemini,"SSAS, analytical, data analysis, TFS, Azure, A...","Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram...",https://www.naukri.com/job-listings-msbi-cosmo...
11,Business Analyst,Business Analyst,Fidelis Corporate Solutions Pvt Ltd,"Jana, Power point, Power BI, Python, MS Office...","Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",https://www.naukri.com/job-listings-business-a...
12,RPA | UiPath Business Analyst,No details available,HCL,"Rpa, Uipath, Business Analysis, Visio, analyti...","Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR",https://www.naukri.com/job-listings-rpa-uipath...
13,Senior Product Analyst / Associate Director - ...,Head - Analytics / BI,TalentStack,"BigQuery, Product Analytics, SQL, R, Product O...","Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru",https://www.naukri.com/job-listings-senior-pro...
14,Business Analyst,Business Analyst,Shujabits Infotech Solutions,"SQL queries, Wireframing, User Experience desi...","Kolkata, Mumbai, Hyderabad/Secunderabad, Chenn...",https://www.naukri.com/job-listings-business-a...
15,We are hiring ESG Data Analyst!!!,Data Analyst,STRAIVE (SPI TECHNOLOGIES),"Rating, Data Analysis, esg, Data Extraction, Q...","Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",https://www.naukri.com/job-listings-we-are-hir...
16,AWS Data Engineer,No details available,Virtusa,"Lambda, modeling, YARN, Kafka, AWS, Big Data, ...","Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram...",https://www.naukri.com/job-listings-aws-data-e...
17,Retail- Analytics Consultant,Analytics Consultant,AVE-Promagne,"Operations & Planning, Customer / CRM, Marketi...","Noida, Kota, Mumbai, New Delhi, Lucknow, Gurga...",https://www.naukri.com/job-listings-retail-ana...
18,Business Analyst,Business Analyst,Fractal Analytics,"Supply chain, Data validation, SAP, Artificial...","Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru",https://www.naukri.com/job-listings-business-a...
19,Consultant,Business Analyst,Fractal Analytics,"Sap, Project Management, Qlik Sense, Bi, Busin...","Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru",https://www.naukri.com/job-listings-consultant...

In [411]:
import time

driver = webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
time.sleep(2)

url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

In [414]:
bookrank = []
booktitle = []
bookauthor = []
bookvolumesales = []
bookpublisher = []
bookgenre = []

try:
    bookrankdriver = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[1]")
    for rank in bookrankdriver:
        bookrank.append(rank.text)
except NoSuchElementException:
    bookrank.append('No details available')

try:
    booktitledriver = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for title in booktitledriver:
        booktitle.append(title.text)
except NoSuchElementException:
    booktitle.append('No details available')
    

try:
    bookauthordriver = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for author in bookauthordriver:
        bookauthor.append(author.text)
except NoSuchElementException:
    bookauthor.append('No details available')
        
try:
    bookvolumesalesdriver = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for volume in bookvolumesalesdriver:
        bookvolumesales.append(volume.text)
except NoSuchElementException:
    bookvolumesales.append('No details available')    
    
try:
    bookpublisherdriver = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for publisher in bookpublisherdriver:
        bookpublisher.append(publisher.text)
except NoSuchElementException:
    bookpublisher.append('No details available')  
    
try:
    bookgenredriver = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for genre in bookgenredriver:
        bookgenre.append(genre.text)
except NoSuchElementException:
    bookgenre.append('No details available')  
    

booklist = pd.DataFrame()
booklist ['Rank'] = bookrank
booklist ['Title'] = booktitle
booklist ['Author'] = bookauthor
booklist ['Sales in Volume'] = bookvolumesales
booklist ['Publisher'] = bookpublisher
booklist ['Genre'] = bookgenre
booklist.head(10)

,Rank,Title,Author,Sales in Volume,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
5,6,Harry Potter and the Goblet of Fire,"Rowling, J.K.","3,583,215",Bloomsbury,Children's Fiction
6,7,Harry Potter and the Chamber of Secrets,"Rowling, J.K.","3,484,047",Bloomsbury,Children's Fiction
7,8,Harry Potter and the Prisoner of Azkaban,"Rowling, J.K.","3,377,906",Bloomsbury,Children's Fiction
8,9,Angels and Demons,"Brown, Dan","3,193,946",Transworld,"Crime, Thriller & Adventure"
9,10,Harry Potter and the Half-blood Prince:Childre...,"Rowling, J.K.","2,950,264",Bloomsbury,Children's Fiction

In [415]:
import time

driver = webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
time.sleep(2)

url = "https://www.imdb.com/list/ls095964455/"
driver.get(url)
time.sleep(2)

In [442]:
seriesname = []
seriesyearsspan = []
seriesgenre = []
seriesruntime = []
seriesratings = []
seriesvotes = []

try:
    namedriver = driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for name in namedriver [:10]:
        seriesname.append(name.text)
except NoSuchElementException:
    seriesname.append('No details available')

try:
    seriesyearsspandriver = driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for years in seriesyearsspandriver [:10]:
        seriesyearsspan.append(years.text)
except NoSuchElementException:
    seriesyearsspan.append('No details available')

try:
    seriesgenredriver = driver.find_elements_by_xpath("//p[@class='text-muted text-small']/span[5]")
    for genre in seriesgenredriver [:10]:
        seriesgenre.append(genre.text)
except NoSuchElementException:
    seriesgenre.append('No details available')

try:
    seriesruntimedriver = driver.find_elements_by_xpath("//p[@class='text-muted text-small']/span[3]")
    for runtime in seriesruntimedriver [:10]:
        seriesruntime.append(runtime.text)
except NoSuchElementException:
    seriesruntime.append('No details available')

try:
    seriesratingsdriver = driver.find_elements_by_xpath("//div[@class='ipl-rating-widget']/div/span[2]")
    for ratings in seriesratingsdriver [:10]:
        seriesratings.append(ratings.text)
except NoSuchElementException:
    seriesratings.append('No details available')        

try:
    seriesvotesdriver = driver.find_elements_by_xpath("//span[@name='nv']")
    for votes in seriesvotesdriver [:10]:
        seriesvotes.append(votes.text)
except NoSuchElementException:
    seriesvotes.append('No details available')
    

seriesvotes


imdblist = pd.DataFrame()
imdblist ['Name'] = seriesname
imdblist ['Years Span'] = seriesyearsspan
imdblist ['Genre'] = seriesgenre
imdblist ['Run Time'] = seriesruntime
imdblist ['Ratings'] = seriesratings
imdblist ['Votes'] = seriesvotes
imdblist.head(10)

,Name,Years Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,957,638"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"967,213"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"932,500"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"279,171"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"239,352"
5,Orange Is the New Black,(2013–2019),"Comedy, Crime, Drama",59 min,8,"293,216"
6,Riverdale,(2017– ),"Crime, Drama, Mystery",45 min,6.7,"137,266"
7,Grey's Anatomy,(2005– ),"Drama, Romance",41 min,7.5,"288,582"
8,The Flash,(2014– ),"Action, Adventure, Drama",43 min,7.6,"333,319"
9,Arrow,(2012–2020),"Action, Adventure, Crime",42 min,7.5,"423,560"

In [445]:
import time

driver = webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
time.sleep(2)

url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

alldatasetbtn = driver.find_element_by_xpath("/html/body/table[1]/tbody/tr/td[2]/span[2]/a")
alldatasetbtn.click()

time.sleep(2)

In [456]:
datasetname = []
datatypes = []
datatask = []
dataattributetype = []
noofinstances = []
noofattribute = []
datasetyear = []

try:
    datasetnamedriver = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for name in datasetnamedriver [:9]:
        datasetname.append(name.text)
except NoSuchElementException:
    datasetname.append('No details available')

try:
    datatypesdriver = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for types in datatypesdriver [1:10]:
        datatypes.append(types.text)
except NoSuchElementException:
    datatypes.append('No details available')
    
try:
    datataskdriver = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for task in datataskdriver [1:10]:
        datatask.append(task.text)
except NoSuchElementException:
    datatask.append('No details available')
    
try:
    dataattributetypedriver = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for attribute in dataattributetypedriver [1:10]:
        dataattributetype.append(attribute.text)
except NoSuchElementException:
    dataattributetype.append('No details available')    
    
try:
    noofinstancesdriver = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for instances in noofinstancesdriver [1:10]:
        noofinstances.append(instances.text)
except NoSuchElementException:
    noofinstances.append('No details available')    

try:
    noofattributedriver = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for attrb in noofattributedriver [1:10]:
        noofattribute.append(attrb.text)
except NoSuchElementException:
    noofattribute.append('No details available')    

try:
    datasetyeardriver = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for year in datasetyeardriver [1:10]:
        datasetyear.append(year.text)
except NoSuchElementException:
    datasetyear.append('No details available')    




datasetlist = pd.DataFrame()
datasetlist ['Data Set Name'] = datasetname
datasetlist ['Data Types'] = datatypes
datasetlist ['Data Task'] = datatask
datasetlist ['Attribute Type'] = dataattributetype
datasetlist ['No of Instances'] = noofinstances
datasetlist ['No of Attribute'] = noofattribute
datasetlist ['Year'] = datasetyear
datasetlist

,Data Set Name,Data Types,Data Task,Attribute Type,No of Instances,No of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
5,Artificial Characters,Multivariate,Classification,"Categorical, Integer, Real",6000,7,1992
6,Audiology (Original),Multivariate,Classification,Categorical,226,,1987
7,Audiology (Standardized),Multivariate,Classification,Categorical,226,69,1992
8,Auto MPG,Multivariate,Regression,"Categorical, Real",398,8,1993

In [497]:
url = "https://www.guru99.com/"
page = requests.get(url)
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

error = driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a').get_attribute('href')
driver.get(error)
time.sleep(3)
exception = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href')
driver.get(exception)

Data = []
table = driver.find_elements_by_xpath("//table[@class='table table-striped']//td")
for i in table:
    try:
        Data.append(i.text)
    except NoSuchElementException:
        Data.append('-')

Name = []
for i in range(2,len(Data),2):
    Name.append(Data[i])

Description = []
for i in range(3,len(Data),2):
    Description.append(Data[i])

df=pd.DataFrame({"Exception name": Name, "Exception description": Description})
df

Legality Response number from our URL is: <Response [403]>

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...