In [9]:
import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [10]:
shoes = webdriver.Chrome('chromedriver.exe')

In [11]:
url = "https://www.flipkart.com/"
shoes.get(url)

In [12]:
prod_search = shoes.find_element_by_class_name('_3704LK')
prod_search

In [13]:
prod_search.send_keys('sneakers')

In [15]:
submit_button = shoes.find_element_by_xpath('/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
submit_button

In [16]:
submit_button.click()

In [102]:
brand_name1 = shoes.find_elements_by_xpath('//div[@class="_2WkVRV"]')
prod_name1_1 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[:4]
prod_name1_2 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[:1]
prod_name1_3 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[4:5]
prod_name1_4 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[1:2]
prod_name1_5 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[5:16]
prod_name1_6 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[2:3]
prod_name1_7 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[16:19]
prod_name1_8 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[3:4]
prod_name1_9 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[19:23]
prod_name1_10 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[4:5]
prod_name1_11 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[23:24]
prod_name1_12 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[5:6]
prod_name1_13 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[24:28]
prod_name1_14 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[6:7]
prod_name1_15 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[28:]
prod_name1_16 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[7:]
prod_price1 = shoes.find_elements_by_xpath('//div[@class="_30jeq3"]')
prod_price1

[<selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="ce3a7a8d-64ad-4f21-9748-1a9a990da9f7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="590954e8-4f2e-49bb-9430-d325a1e0d01a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="de5cf0ef-5e2b-4460-8294-d21a6c6a0b82")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="3ac86053-ed3f-4c38-ba19-8efcfbe038d8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="ef827b41-c63c-4de9-b6c2-8ef6669b74a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="adcd6f7e-01ed-4ab6-8dd8-ecabd3ab0a86")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="cb453514-bf66-41e5-9745-e88b20fba29f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="e9e76928-c2da-4681-86f4-c92bd8735fd1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="fb061605-49fb-4688-831e-18dea622805f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="98cabfc2-53f9-43a9-a883-7c1bf36e3463")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="eaffe998-faa5-49b8-ac8f-7e3ad1f30faa")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="4f83a44d-3899-49e8-b745-673d1cb6bf3e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="e5d6bfdb-1884-4350-a331-8975a4c66b60")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="983bb97f-975e-4857-a22d-44a8f785fd17")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="b19b45dc-7bfc-4051-b4a7-b1db7e9b809f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="8d772d7a-c4fc-4b25-83c2-71cbd314379b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="58b1fab8-ce50-4666-8d9a-67cb0147be0b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="50cda36e-f034-47cc-ad68-319bd1e7dbb0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="7d224fd0-6c83-418b-9284-ee84f7791aaa")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="f2b48f66-b027-435b-8748-765e952b212b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="45a1da64-c83a-4a32-ba27-e2c7686cd2a4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="425341ed-0a73-4362-8d4b-4d3003945cd1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="62fa55e5-c7a3-48c6-970b-002ec682d2d2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="07057324-501e-4063-aad6-77a0bd2d1bd9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="b1360ba1-56ca-462d-b28b-4c380083bd06")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="a75d5697-05e4-4f29-9e96-e2689555ae3d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="ce0a1fb6-2109-4831-b9ad-1f3cf3af1422")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="69c8f953-50ca-4c41-8a44-47b58e0dbc61")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="b2db4935-0f78-4b07-bab9-ee7199e15169")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="5c3fc2d2-3b26-43b9-bbb9-4dfbdf3428ee")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="dd00d407-8d3a-4492-bd3e-28e1af5618ab")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="76d790a4-d56c-4387-8edb-01568225427e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="52ced682-01fd-420d-946d-79a5eb3508e1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="a6c70c4e-59bd-46e8-9cf6-e76b4965a8ee")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="13c94413-0888-48cc-ad26-3690eefc8b8e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="0455d666-6515-4ca8-89a7-3290ae83400b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="a86f2939-91bd-49f8-9831-eba8998b893d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="05dc1165-3f5a-42f1-96a1-5598c58685b4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="043d3086-4d18-4bbf-b5a5-784624360e7e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="a4340dd5-3634-48fe-b1fd-ec1c5aaedbdf")>]

In [103]:
Brandname = []

for name in brand_name1:
    Brandname.append(name.text)
Brandname

Prodname1 = []

for pname in prod_name1_1:
    Prodname1.append(pname.text)
Prodname1

Prodname2 = []

for pname in prod_name1_2:
    Prodname2.append(pname.text)
Prodname2

Prodname3 = []

for pname in prod_name1_3:
    Prodname3.append(pname.text)
Prodname3

Prodname4 = []

for pname in prod_name1_4:
    Prodname4.append(pname.text)
Prodname4

Prodname5 = []

for pname in prod_name1_5:
    Prodname5.append(pname.text)
Prodname5

Prodname6 = []

for pname in prod_name1_6:
    Prodname6.append(pname.text)
Prodname6

Prodname7 = []

for pname in prod_name1_7:
    Prodname7.append(pname.text)
Prodname7

Prodname8 = []

for pname in prod_name1_8:
    Prodname8.append(pname.text)
Prodname8

Prodname9 = []

for pname in prod_name1_9:
    Prodname9.append(pname.text)
Prodname9

Prodname10 = []

for pname in prod_name1_10:
    Prodname10.append(pname.text)
Prodname10

Prodname11 = []

for pname in prod_name1_11:
    Prodname11.append(pname.text)
Prodname11

Prodname12 = []

for pname in prod_name1_12:
    Prodname12.append(pname.text)
Prodname12

Prodname13 = []

for pname in prod_name1_13:
    Prodname13.append(pname.text)
Prodname13

Prodname14 = []

for pname in prod_name1_14:
    Prodname14.append(pname.text)
Prodname14

Prodname15 = []

for pname in prod_name1_15:
    Prodname15.append(pname.text)
Prodname15

Prodname16 = []

for pname in prod_name1_16:
    Prodname16.append(pname.text)
Prodname16

ProdusctDescription = list(Prodname1+Prodname2+Prodname3+Prodname4+Prodname5+Prodname6+Prodname7+Prodname8+Prodname9+Prodname10+Prodname11+Prodname12+Prodname13+Prodname14+Prodname15+Prodname16)
ProdusctDescription

Prodprice1 = []

for pprice in prod_price1:
    Prodprice1.append(pprice.text)
Prodprice1

['₹449',
 '₹499',
 '₹398',
 '₹449',
 '₹220',
 '₹499',
 '₹242',
 '₹449',
 '₹948',
 '₹499',
 '₹348',
 '₹449',
 '₹359',
 '₹398',
 '₹345',
 '₹442',
 '₹499',
 '₹298',
 '₹449',
 '₹598',
 '₹499',
 '₹499',
 '₹189',
 '₹499',
 '₹499',
 '₹299',
 '₹379',
 '₹499',
 '₹499',
 '₹399',
 '₹429',
 '₹499',
 '₹599',
 '₹574',
 '₹299',
 '₹499',
 '₹649',
 '₹499',
 '₹499',
 '₹898']

In [105]:
data = pd.DataFrame()
data ['Brand Name'] = Brandname
data ['Prod Desc'] = ProdusctDescription
data ['Price'] = Prodprice1
data.head(45)

         Brand Name                                          Prod Desc Price
0             AMICO                                   Sneakers For Men  ₹449
1     RODDICK SHOES  Fashion Outdoor Canvas Casual Light Weight Lac...  ₹499
2          Magnolia                                   Sneakers For Men  ₹398
3    luxury fashion  Luxury Fashionable casual sneaker shoes Sneake...  ₹449
4          URBANBOX                          Sneakers Sneakers For Men  ₹220
5            Labbin                                   Sneakers For Men  ₹499
6      Stefano Rads                            Classy Sneakers For Men  ₹242
7         India hub   luxury fashionable casual shoes Sneakers For Men  ₹449
8            Extoes  Modern Trendy Shoes Combo pack of 4 Sneakers F...  ₹948
9             Jabra  Perfect Combo Sport Shoes for Running Training...  ₹499
10       D-SNEAKERZ  Casual , Partywear Sneakers Shoes For Men's An...  ₹348
11            AMICO                                   Sneakers For Men  ₹449
12        Trendmode                                   Sneakers For Men  ₹359
13        SCATCHITE                          Sneakers Sneakers For Men  ₹398
14       Shoes Bank     White Sneaker For Men's/Boy's Sneakers For Men  ₹345
15            BIRDE                  Men Casual Shoes Sneakers For Men  ₹442
16         ASTEROID  Original Luxury Branded Fashionable Men's Casu...  ₹499
17         HOTSTYLE                                   Sneakers For Men  ₹298
18            Pieds                                   Sneakers For Men  ₹449
19            BIRDE      Combo Pack of 2 Casual Shoes Sneakers For Men  ₹598
20          Numenzo                        411 Casual Sneakers For Men  ₹499
21           Kraasa                          Series 7 Sneakers For Men  ₹499
22  ganpati traders                                   Sneakers For Men  ₹189
23    RODDICK SHOES  Fashion Outdoor Canvas Casual Light Weight Lac...  ₹499
24            Echor  Men's Sneakers Fashion Lightweight Running Sho...  ₹499
25            BIRDE              Sports Running Shoes Sneakers For Men  ₹299
26           BRUTON               Modern Trendy Shoes Sneakers For Men  ₹379
27    RODDICK SHOES  Fashion Outdoor Canvas Casual Light Weight Lac...  ₹499
28     Robbie jones                                   Sneakers For Men  ₹499
29            Arohi                                   Sneakers For Men  ₹399
30          Numenzo             White Sneaker For Men Sneakers For Men  ₹429
31            AMICO  Designer Printed Casual Sneakers Shoes Sneaker...  ₹499
32               TR                                   Sneakers For Men  ₹599
33           Rzisbo                                   Sneakers For Men  ₹574
34          Lee Won                           FASHION Sneakers For Men  ₹299
35    RODDICK SHOES  Fashion Outdoor Canvas Casual Light Weight Lac...  ₹499
36            CLYMB                                   Sneakers For Men  ₹649
37        India hub  Luxury Fashionable casual sneaker shoes Sneake...  ₹499
38           Kraasa                          Shark-41 Sneakers For Men  ₹499
39         Roadster                                   Sneakers For Men  ₹898

In [113]:
np_button = shoes.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[2]')
np_button

In [114]:
np_button.click()

In [140]:
brand_name2 = shoes.find_elements_by_xpath('//div[@class="_2WkVRV"]')
prod_name2_1 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[:6]
prod_name2_2 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[:3]
prod_name2_3 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[6:10]
prod_name2_4 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[2:3]
prod_name2_5 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[10:26]
prod_name2_6 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[3:4]
prod_name2_7 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[25:26]
prod_name2_8 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[5:]
prod_name2_9 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[27:]
prod_price2 = shoes.find_elements_by_xpath('//div[@class="_30jeq3"]')
prod_price2

[<selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="2ec5a999-d4c5-46ec-92da-cc192d7527d5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="dece1797-9746-4db3-bd49-3ccfea1067cc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="dd845987-2f52-48cf-8b6e-0121d877d633")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="ecb716d5-5a28-4b56-9627-ea6a62807e78")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="138a5b90-c257-4d84-a13f-6bc54d050428")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="1e7169d9-81b3-434a-ba6a-fcf8caffbf40")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="06ed3984-4c94-4547-be8e-8fbe71eda9e4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="9cc651fb-969c-422c-9a3c-1ccb0d729bbf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="c75a8d0c-bb92-4908-9bab-e7b2b8143c5a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="880a453d-e7a0-4c2f-bad0-b0b8c95a5695")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="cbba560d-0fc3-4d0e-86d8-602898f4c816")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="4e1c4a21-e4ee-4aab-b133-a02e2bbd45db")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="ec8102ba-4995-4404-bd3f-3c7653131cea")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="f5d35e8c-e14e-470e-805c-70335fb2c77b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="dc56060b-ed0e-4f14-ae17-9fba5c437dfd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="904f9d88-d051-448e-a548-e506fcd89e04")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="10d630bd-849c-4994-b99a-f66d9f74cc82")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="646144a5-5224-41b7-86d6-84b7c437a5f0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="320720ed-edd0-481d-9650-33f7164cdf4e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="d6094f80-aa60-42cb-9c51-9b399d5827b0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="bfeff9b7-de58-48a7-909d-4c0a7dddcf9c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="5ce09295-abe1-46de-a52b-224fb8f79e02")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="0735b601-95ea-4e10-969f-953de31a997c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="3c5a5cb6-c7b3-4e3a-a7be-2757207fcfb7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="b8e43890-3380-4cf8-b8be-4cdc6d56d870")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="57378fcb-a201-4636-8424-9c700d7196d0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="252b041e-a4ab-4a7a-ad76-4a172d3224f8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="ba6eabd7-3d95-414b-b821-fa70baa51a8d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="df71d420-8f07-4ebe-b22a-389e5cce08e2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="ca6158c7-dde5-4dbc-a03c-816fa7abe410")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="1defa449-53ec-44d3-b7a5-61b6ffb9eef2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="cdc1fd13-6181-4877-9bba-6aceef1420a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="dfb84628-5bad-47b2-9c74-d38eb5278aab")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="96efaeb4-13bb-4124-a40d-9cd3894b31a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="6de36cda-6d70-46e8-8afa-4dd76f06aabc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="629cc473-afc9-402e-84a8-16b3801b9525")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="3d78faa3-694f-4c14-b4ca-64e01ab74597")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="84854622-2127-4fcb-9bdb-51d6b077f457")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="16c25024-526b-4124-8f50-128929e77fc2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="aed75d45-a215-413d-a625-08a558f0991c")>]

In [147]:
Brandname1 = []

for name in brand_name2:
    Brandname1.append(name.text)
Brandname1

Prodname1 = []

for pname in prod_name2_1:
    Prodname1.append(pname.text)
Prodname1

Prodname2 = []

for pname in prod_name2_2:
    Prodname2.append(pname.text)
Prodname2

Prodname3 = []

for pname in prod_name2_3:
    Prodname3.append(pname.text)
Prodname3

Prodname4 = []

for pname in prod_name2_4:
    Prodname4.append(pname.text)
Prodname4

Prodname5 = []

for pname in prod_name2_5:
    Prodname5.append(pname.text)
Prodname5

Prodname6 = []

for pname in prod_name2_6:
    Prodname6.append(pname.text)
Prodname6

Prodname7 = []

for pname in prod_name2_7:
    Prodname7.append(pname.text)
Prodname7

Prodname8 = []

for pname in prod_name2_8:
    Prodname8.append(pname.text)
Prodname8

Prodname9 = []

for pname in prod_name2_9:
    Prodname9.append(pname.text)
Prodname9

ProdusctDescription1 = list(Prodname1+Prodname2+Prodname3+Prodname4+Prodname5+Prodname6+Prodname7+Prodname8+Prodname9)
ProdusctDescription1

Prodprice2 = []

for pprice in prod_price2:
    Prodprice2.append(pprice.text)
Prodprice2

['₹399',
 '₹199',
 '₹499',
 '₹479',
 '₹451',
 '₹298',
 '₹680',
 '₹749',
 '₹799',
 '₹438',
 '₹489',
 '₹499',
 '₹555',
 '₹799',
 '₹399',
 '₹699',
 '₹499',
 '₹449',
 '₹499',
 '₹920',
 '₹2,998',
 '₹429',
 '₹920',
 '₹920',
 '₹599',
 '₹448',
 '₹245',
 '₹920',
 '₹499',
 '₹499',
 '₹640',
 '₹399',
 '₹630',
 '₹499',
 '₹498',
 '₹2,899',
 '₹367',
 '₹599',
 '₹499',
 '₹499']

In [148]:
data1 = pd.DataFrame()
data1 ['Brand Name'] = Brandname1
data1 ['Prod Desc'] = ProdusctDescription1
data1 ['Price'] = Prodprice2
data1.head(45)

,Brand Name,Prod Desc,Price
0,ESSENCE,Casuals Sneakers For Women,₹399
1,World Wear Footwear,Latest Collection-1216 Stylish Casual Sports S...,₹199
2,ASTEROID,Original Luxury Branded Fashionable Men's Casu...,₹499
3,PEHANOSA,Sneakers For Men,₹479
4,Robbie jones,Casual Sneakers Black Shoes For Men Sneakers F...,₹451
5,RINDAS,Perfect Stylish Casual Shoes For Girls & Women...,₹298
6,RapidBox,Sneakers For Men,₹680
7,FOOTSTAIR,Sneakers For Men,₹749
8,SPARX,SM-439 Sneakers For Men,₹799
9,RINDAS,Sneakers For Women,₹438
10,K- FOOTLANCE,Sneakers For Men,₹489
11,Zapatoz,Sneakers For Women,₹499
12,Kraasa,Shark-41 Sneakers For Men,₹555
13,SPARX,SM-439 Sneakers For Men,₹799
14,aadi,Sneakers For Men,₹399
15,SORT,Unisex Comfortable Casual Daily Wear | Gym Sne...,₹699
16,believe,Sneakers for men(black_6) Sneakers For Men,₹499
17,DUNKASTON,Sneakers For Men,₹449
18,Robbie jones,Sneakers For Men,₹499
19,Advick,Sneakers For Men,₹920
20,PUMA,Glory Sneakers For Men,"₹2,998"
21,India hub,Luxury Fashionable casual sneaker shoes Sneake...,₹429
22,SPARX,SM-322 Sneakers For Men,₹920
23,Advick,Sneakers For Men,₹920
24,World Wear Footwear,Combo Pack of 4 Latest Collection Stylish Casu...,₹599
25,MILESWALKER,Stylish Casual Sports Shoe Sneakers For Women ...,₹448
26,Kreverse,Sneakers For Men,₹245
27,Advick,Sneakers For Men,₹920
28,Zorth,Sneakers For Men,₹499
29,Xtoon,"white Casual shoes,Sneakers for men's Sneakers...",₹499
30,RapidBox,SM439G Sneakers For Men,₹640
31,RealToes,"white Casual shoes,Sneakers for men's Sneakers...",₹399
32,RapidBox,Stylish & Trendy Sneakers For Men,₹630
33,Echor,Echor Men's Sneakers Fashion Lightweight Runni...,₹499
34,Zorth,Sneakers For Men,₹498
35,FILA,RICO Sneakers For Men,"₹2,899"
36,HRDK,Sneakers For Men,₹367
37,BIRDE,Combo Pack of 2 Casual shoes Sneakers For Men,₹599
38,RODDICK SHOES,Fashion Outdoor Canvas Casual Light Weight Lac...,₹499
39,ZAPPY,Women's and Girl's Stylish Casual Shoes |Rubbe...,₹499

In [150]:
np_button1 = shoes.find_element_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[4]')
np_button1

In [151]:
np_button1.click()

In [177]:
brand_name3 = shoes.find_elements_by_xpath('//div[@class="_2WkVRV"]')[:20]
prod_name3_1 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[:13]
prod_name3_2 = shoes.find_elements_by_xpath('//a[@class="IRpwTa _2-ICcC"]')[:2]
prod_name3_3 = shoes.find_elements_by_xpath('//a[@class="IRpwTa"]')[13:18]
prod_price3 = shoes.find_elements_by_xpath('//div[@class="_30jeq3"]')[:20]
prod_price3

[<selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="f5846d83-ccd5-496f-a124-20d34aa9c801")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="3ddb7f5f-07ef-453c-9309-84bb4bf0d968")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="7a066899-ec97-44db-a325-f9ca132de2d8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="4133baa1-5792-41ba-84bc-266b1e1d0f54")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="f19b139c-bd38-4c83-aff4-043b11bfa5e9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="50787d18-7f89-4529-894a-3989fe1617ef")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="4dc477cd-dc05-4fc0-88c0-dea2f01e1bd7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="24ff8d75-8e47-4b31-8d91-f87827df3943")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="c8718d71-cf8a-4498-a252-5c209a0b1909")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="b04ea6fe-a22f-4e71-a2e8-21fc5d989e4d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="9d61feb2-5f84-44e3-81fb-eea982a00e69")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="e3e755cb-d709-4456-9a0c-7099a8789a4f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="b8377f14-bf0e-4515-922b-e10e9857205f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="cab18fb6-c726-4797-8494-5312fcd6174d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="c74bba81-7581-4ea5-829c-4eff330ba5de")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="e34a1b51-42f0-4333-8715-9ad27546a9e9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="9b1a1a5e-d0f1-4817-88a9-3d685a104a5d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="fd4fb535-96fc-4bd5-94b0-ecd6de3a86cc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="ddcf42e0-930c-40c8-b0c9-ad9f02a0ac05")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ec4d9e805a3179aa35214c73b179e62", element="a2742ad8-bb0d-49a3-8459-8b0f241f1a15")>]

In [183]:
Brandname2 = []

for name in brand_name3:
    Brandname2.append(name.text)
Brandname2

Prodname1 = []

for pname in prod_name3_1:
    Prodname1.append(pname.text)
Prodname1

Prodname2 = []

for pname in prod_name3_2:
    Prodname2.append(pname.text)
Prodname2

Prodname3 = []

for pname in prod_name3_3:
    Prodname3.append(pname.text)
Prodname3

ProdusctDescription2 = list(Prodname1+Prodname2+Prodname3)
ProdusctDescription2

Prodprice3 = []

for pprice in prod_price3:
    Prodprice3.append(pprice.text)
Prodprice3

['₹892',
 '₹2,199',
 '₹384',
 '₹569',
 '₹399',
 '₹749',
 '₹386',
 '₹499',
 '₹427',
 '₹499',
 '₹474',
 '₹442',
 '₹599',
 '₹429',
 '₹649',
 '₹499',
 '₹499',
 '₹699',
 '₹598',
 '₹549']

In [184]:
data2 = pd.DataFrame()
data2 ['Brand Name'] = Brandname2
data2 ['Prod Desc'] = ProdusctDescription2
data2 ['Price'] = Prodprice3
data2.head(45)

        Brand Name                                          Prod Desc   Price
0            SPARX                            SM-162 Sneakers For Men    ₹892
1             PUMA  Puma Smash v2 L Perf Puma White-Puma Whi Sneak...  ₹2,199
2       D-SNEAKERZ  Casual , Partywear Sneakers Shoes For Men's An...    ₹384
3            Echor  Echor Men's Sneakers Fashion Lightweight Runni...    ₹569
4         KANEGGYE                                   Sneakers For Men    ₹399
5         Vellinto            Casual Sneakrs For Men Sneakers For Men    ₹749
6            Echor  Men's Canvas Low Top Sneakers Lace-up Classic ...    ₹386
7      MILESWALKER                                 Sneakers For Women    ₹499
8        Deals4you                                 Sneakers For Women    ₹427
9           VENDOZ  Girls Stylish Casual Sports Shoe Sneakers For ...    ₹499
10    Robbie jones  Casual Sneakers White Shoes For Men Sneakers F...    ₹474
11        PEHANOSA                                   Sneakers For Men    ₹442
12          BRUTON  Modern & Trendy Collection Combo Pack of 02 Sh...    ₹599
13          FEWROK                   Premium quality Sneakers For Men    ₹429
14  KNIGHT WALKERS                                   Sneakers For Men    ₹649
15         Zapatoz                                 Sneakers For Women    ₹499
16           ASIAN  Skypy-31 Walking Shoes,Training Shoes,Sneakers...    ₹499
17           CLYMB                                   Sneakers For Men    ₹699
18           BIRDE      Combo Pack of 2 Casual Shoes Sneakers For Men    ₹598
19             GVR                                   Sneakers For Men    ₹549

In [185]:
pd.concat([data, data1, data2])

        Brand Name                                          Prod Desc Price
0            AMICO                                   Sneakers For Men  ₹449
1    RODDICK SHOES  Fashion Outdoor Canvas Casual Light Weight Lac...  ₹499
2         Magnolia                                   Sneakers For Men  ₹398
3   luxury fashion  Luxury Fashionable casual sneaker shoes Sneake...  ₹449
4         URBANBOX                          Sneakers Sneakers For Men  ₹220
..             ...                                                ...   ...
15         Zapatoz                                 Sneakers For Women  ₹499
16           ASIAN  Skypy-31 Walking Shoes,Training Shoes,Sneakers...  ₹499
17           CLYMB                                   Sneakers For Men  ₹699
18           BIRDE      Combo Pack of 2 Casual Shoes Sneakers For Men  ₹598
19             GVR                                   Sneakers For Men  ₹549

[100 rows x 3 columns]