In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import selenium
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import time
from webdriver_manager.chrome import ChromeDriverManager
import re

In [2]:
driver = webdriver.Chrome('chromedriverv99.exe')
time.sleep(2)

url = "https://www.cars24.com/"
driver.get(url)
driver.maximize_window()

In [3]:
selectmanually = driver.find_element_by_xpath("/html/body/div[1]/div[10]/div/div/div/div[2]/div[2]/button")
selectmanually
selectmanually.click()

time.sleep(2)

In [4]:
selectcity = driver.find_element_by_xpath("/html/body/div[1]/div[10]/div/div/div/div[2]/ul/li[1]/span/img")
selectcity
selectcity.click()

time.sleep(2)

In [5]:
viewcars = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[2]/div/span")
viewcars
viewcars.click()

for _ in range(170):
    driver.execute_script("window.scrollBy(0,170)")
time.sleep(5)

In [6]:
urls = []

urldriver = driver.find_elements_by_xpath("//div[@class='col-4']/a")

for link in urldriver:
    urls.append(link.get_attribute('href'))
urls

['https://www.cars24.com/buy-used-maruti-swift-dzire-2013-cars-noida-1008693808/',
 'https://www.cars24.com/buy-used-toyota-etios-2011-cars-new-delhi-1002347243/',
 'https://www.cars24.com/buy-used-maruti-zen-estilo-2009-cars-faridabad-1010676821/',
 'https://www.cars24.com/buy-used-maruti-zen-estilo-2009-cars-gurgaon-1002666227/',
 'https://www.cars24.com/buy-used-volkswagen-vento-2014-cars-new-delhi-1002641704/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2013-cars-new-delhi-2333449808/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2013-cars-new-delhi-1007895707/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2013-cars-new-delhi-1054649947/',
 'https://www.cars24.com/buy-used-maruti-swift-2012-cars-new-delhi-1003461909/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2013-cars-new-delhi-1006676624/',
 'https://www.cars24.com/buy-used-maruti-ritz-2010-cars-faridabad-1120065822/',
 'https://www.cars24.com/buy-used-ford-freestyle-2018-cars-sonipat-1157152968/',
 'https://www.cars24.com/buy-used-maruti-s-cross-2016-cars-faridabad-1002987041/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2014-cars-new-delhi-1018057844/',
 'https://www.cars24.com/buy-used-maruti-alto-k10-2019-cars-new-delhi-1006618561/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2014-cars-noida-1002709502/',
 'https://www.cars24.com/buy-used-maruti-swift-2013-cars-new-delhi-1001623644/',
 'https://www.cars24.com/buy-used-hyundai-i20-2013-cars-faridabad-1005662020/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2014-cars-new-delhi-1009223046/',
 'https://www.cars24.com/buy-used-maruti-wagon-r-1.0-2013-cars-new-delhi-1002853706/',
 'https://www.cars24.com/buy-used-maruti-alto-800-2012-cars-new-delhi-1002922226/',
 'https://www.cars24.com/buy-used-audi-q3-2014-cars-new-delhi-1003134925/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2014-cars-noida-1010603849/',
 'https://www.cars24.com/buy-used-maruti-swift-2014-cars-faridabad-1005299843/',
 'https://www.cars24.com/buy-used-maruti-ertiga-2014-cars-faridabad-1007019907/',
 'https://www.cars24.com/buy-used-maruti-dzire-2017-cars-gurgaon-1019887105/',
 'https://www.cars24.com/buy-used-maruti-ertiga-2017-cars-gurgaon-1018481749/',
 'https://www.cars24.com/buy-used-hyundai-verna-2013-cars-noida-1005933609/',
 'https://www.cars24.com/buy-used-ford-ecosport-2013-cars-new-delhi-1004800442/',
 'https://www.cars24.com/buy-used-honda-amaze-2015-cars-gurgaon-1016908760/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-new-delhi-1000173927/',
 'https://www.cars24.com/buy-used-toyota-innova-2014-cars-new-delhi-1005025041/',
 'https://www.cars24.com/buy-used-mahindra-scorpio-2019-cars-faridabad-1019167145/',
 'https://www.cars24.com/buy-used-maruti-swift-2013-cars-gurgaon-1056780922/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2016-cars-noida-1480350123/',
 'https://www.cars24.com/buy-used-maruti-ciaz-2017-cars-new-delhi-1007192623/',
 'https://www.cars24.com/buy-used-maruti-swift-2014-cars-new-delhi-1007283406/',
 'https://www.cars24.com/buy-used-toyota-fortuner-2013-cars-gurgaon-1009538340/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2015-cars-new-delhi-1106443844/',
 'https://www.cars24.com/buy-used-maruti-swift-2013-cars-new-delhi-1019746822/',
 'https://www.cars24.com/buy-used-maruti-swift-2013-cars-new-delhi-1008059245/',
 'https://www.cars24.com/buy-used-maruti-swift-2014-cars-new-delhi-1057528422/',
 'https://www.cars24.com/buy-used-maruti-swift-2015-cars-gurgaon-1004316921/',
 'https://www.cars24.com/buy-used-maruti-swift-2015-cars-new-delhi-1008560242/',
 'https://www.cars24.com/buy-used-maruti-new--wagon-r-2020-cars-gurgaon-1101796649/',
 'https://www.cars24.com/buy-used-maruti-swift-2014-cars-new-delhi-1009933446/',
 'https://www.cars24.com/buy-used-maruti-swift-2015-cars-noida-1006609108/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2016-cars-new-delhi-1001313245/',
 'https://www.cars24.com/buy-used-honda-city-2018-cars-noida-1129686440/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2016-cars-new-delhi-1000746727/',
 'https://www.cars24.com/buy-used-toyota-fortuner-2013-cars-noida-1017513244/',
 'https://www.cars24.com/buy-used-maruti-ciaz-2017-cars-new-delhi-1007554104/',
 'https://www.cars24.com/buy-used-honda-city-2015-cars-new-delhi-1018930027/',
 'https://www.cars24.com/buy-used-maruti-ciaz-2017-cars-new-delhi-1000909706/',
 'https://www.cars24.com/buy-used-maruti-ciaz-2014-cars-faridabad-1010193341/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2018-cars-noida-1008819848/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2015-cars-new-delhi-1001479501/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-gurgaon-1012563367/',
 'https://www.cars24.com/buy-used-audi-q3-2015-cars-new-delhi-1008120723/',
 'https://www.cars24.com/buy-used-maruti-swift-2015-cars-gurgaon-1009658243/',
 'https://www.cars24.com/buy-used-maruti-swift-2015-cars-gurgaon-1125080422/',
 'https://www.cars24.com/buy-used-honda-city-2012-cars-new-delhi-1016897940/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-new-delhi-1007131707/',
 'https://www.cars24.com/buy-used-bmw-x1-2017-cars-new-delhi-1014511627/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2016-cars-gurgaon-1127596648/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-new-delhi-1010271903/',
 'https://www.cars24.com/buy-used-hyundai-tucson-new-2018-cars-faridabad-1102076426/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2016-cars-new-delhi-1055282341/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2016-cars-new-delhi-1481579246/',
 'https://www.cars24.com/buy-used-toyota-innova-crysta-2017-cars-faridabad-1101348147/',
 'https://www.cars24.com/buy-used-hyundai-creta-2017-cars-noida-1007376925/',
 'https://www.cars24.com/buy-used-renault-duster-2014-cars-new-delhi-1006710945/',
 'https://www.cars24.com/buy-used-ford-ecosport-2015-cars-gurgaon-1003713306/',
 'https://www.cars24.com/buy-used-hyundai-verna-2014-cars-new-delhi-1054979409/',
 'https://www.cars24.com/buy-used-mercedes-benz-cla-class-2015-cars-new-delhi-1009433929/',
 'https://www.cars24.com/buy-used-maruti-baleno-2017-cars-new-delhi-1008448803/',
 'https://www.cars24.com/buy-used-maruti-baleno-2017-cars-new-delhi-1008812142/',
 'https://www.cars24.com/buy-used-ford-ecosport-2017-cars-new-delhi-1154423103/',
 'https://www.cars24.com/buy-used-toyota-fortuner-2015-cars-gurgaon-1008156620/',
 'https://www.cars24.com/buy-used-toyota-fortuner-2013-cars-new-delhi-1008866546/',
 'https://www.cars24.com/buy-used-tata-tiago-2018-cars-new-delhi-1016938300/',
 'https://www.cars24.com/buy-used-toyota-corolla-altis-2014-cars-new-delhi-1104339944/',
 'https://www.cars24.com/buy-used-bmw-x1-2016-cars-new-delhi-1013242120/',
 'https://www.cars24.com/buy-used-mercedes-benz-e-class-2013-cars-new-delhi-1013183521/',
 'https://www.cars24.com/buy-used-ford-ecosport-2016-cars-new-delhi-1100493705/',
 'https://www.cars24.com/buy-used-maruti-alto-800-2017-cars-new-delhi-1000286343/',
 'https://www.cars24.com/buy-used-mahindra-xuv500-2014-cars-new-delhi-1100824922/',
 'https://www.cars24.com/buy-used-hyundai-i20-active-2015-cars-new-delhi-1004628363/',
 'https://www.cars24.com/buy-used-maruti-ignis-2018-cars-new-delhi-1000766143/',
 'https://www.cars24.com/buy-used-nissan-terrano-2014-cars-new-delhi-1018156430/',
 'https://www.cars24.com/buy-used-toyota-etios-2015-cars-faridabad-1100687922/',
 'https://www.cars24.com/buy-used-hyundai-tucson-new-2017-cars-gurgaon-1013133967/',
 'https://www.cars24.com/buy-used-hyundai-i20-active-2015-cars-new-delhi-1003048161/',
 'https://www.cars24.com/buy-used-hyundai-creta-2015-cars-new-delhi-1005729343/',
 'https://www.cars24.com/buy-used-toyota-etios-2015-cars-new-delhi-1000535344/',
 'https://www.cars24.com/buy-used-toyota-innova-2014-cars-new-delhi-1019413323/',
 'https://www.cars24.com/buy-used-honda-city-2014-cars-new-delhi-1003752028/',
 'https://www.cars24.com/buy-used-mercedes-benz-e-class-2013-cars-new-delhi-1002046328/',
 'https://www.cars24.com/buy-used-volkswagen-polo-2016-cars-new-delhi-1000766728/',
 'https://www.cars24.com/buy-used-bmw-x3-2013-cars-new-delhi-1056839842/',
 'https://www.cars24.com/buy-used-mahindra-scorpio-2013-cars-new-delhi-1004298266/',
 'https://www.cars24.com/buy-used-hyundai-xcent-2014-cars-new-delhi-1009915267/',
 'https://www.cars24.com/buy-used-volkswagen-ameo-2017-cars-new-delhi-1006693169/',
 'https://www.cars24.com/buy-used-hyundai-i20-2013-cars-noida-1015936920/',
 'https://www.cars24.com/buy-used-maruti-baleno-2019-cars-new-delhi-1009827301/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2018-cars-new-delhi-1003513100/',
 'https://www.cars24.com/buy-used-mahindra-scorpio-2017-cars-new-delhi-1008858165/',
 'https://www.cars24.com/buy-used-hyundai-tucson-new-2018-cars-new-delhi-1056461660/',
 'https://www.cars24.com/buy-used-maruti-alto-k10-2018-cars-faridabad-1016102108/',
 'https://www.cars24.com/buy-used-hyundai-i10-2010-cars-gurgaon-1106750123/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2018-cars-new-delhi-1006000026/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2018-cars-new-delhi-1019947006/',
 'https://www.cars24.com/buy-used-mahindra-xuv500-2015-cars-new-delhi-1015934424/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2019-cars-faridabad-1001753249/',
 'https://www.cars24.com/buy-used-mahindra-scorpio-2016-cars-gurgaon-1010048667/',
 'https://www.cars24.com/buy-used-maruti-alto-k10-2019-cars-noida-1003205206/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2019-cars-new-delhi-1014699507/',
 'https://www.cars24.com/buy-used-honda-wr-v-2017-cars-new-delhi-1000563268/',
 'https://www.cars24.com/buy-used-bmw-3-series-2015-cars-faridabad-2330550543/',
 'https://www.cars24.com/buy-used-mahindra-xuv500-2013-cars-new-delhi-1003155561/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2018-cars-new-delhi-1005261306/',
 'https://www.cars24.com/buy-used-ford-ecosport-2015-cars-new-delhi-1003687304/',
 'https://www.cars24.com/buy-used-toyota-corolla-altis-2016-cars-gurgaon-1009163145/',
 'https://www.cars24.com/buy-used-maruti-new--wagon-r-2019-cars-noida-1001617666/',
 'https://www.cars24.com/buy-used-ford-new-figo-2017-cars-new-delhi-1009239340/',
 'https://www.cars24.com/buy-used-bmw-x3-2013-cars-new-delhi-1125301409/',
 'https://www.cars24.com/buy-used-volkswagen-polo-2012-cars-new-delhi-1005119541/',
 'https://www.cars24.com/buy-used-maruti-ignis-2019-cars-gurgaon-1003913149/',
 'https://www.cars24.com/buy-used-mahindra-scorpio-2018-cars-new-delhi-1007851769/',
 'https://www.cars24.com/buy-used-toyota-yaris-2018-cars-new-delhi-1004897761/',
 'https://www.cars24.com/buy-used-hyundai-eon-2015-cars-new-delhi-1015767145/',
 'https://www.cars24.com/buy-used-maruti-vitara-brezza-2020-cars-faridabad-1000109840/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2015-cars-noida-1109313969/',
 'https://www.cars24.com/buy-used-honda-civic-2019-cars-new-delhi-1744949000/',
 'https://www.cars24.com/buy-used-hyundai-creta-2016-cars-noida-1123777444/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2015-cars-new-delhi-1000165268/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2015-cars-gurgaon-1014318960/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2015-cars-gurgaon-1018735963/',
 'https://www.cars24.com/buy-used-hyundai-creta-2016-cars-new-delhi-1006036047/',
 'https://www.cars24.com/buy-used-ford-figo-aspire-2015-cars-new-delhi-1005963600/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2015-cars-new-delhi-1008535569/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2015-cars-new-delhi-1003542603/',
 'https://www.cars24.com/buy-used-mahindra-scorpio-2016-cars-gurgaon-1017923961/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-noida-1053343560/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-new-delhi-1006577005/',
 'https://www.cars24.com/buy-used-maruti-dzire-2017-cars-noida-1000646849/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-gurgaon-1009431864/',
 'https://www.cars24.com/buy-used-hyundai-creta-2015-cars-faridabad-1001216726/',
 'https://www.cars24.com/buy-used-hyundai-grand-i10-2017-cars-new-delhi-1009773640/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-new-delhi-1001462449/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-new-delhi-1011351047/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-faridabad-1101005561/',
 'https://www.cars24.com/buy-used-maruti-swift-dzire-2012-cars-faridabad-2334649542/',
 'https://www.cars24.com/buy-used-bmw-5-series-2015-cars-faridabad-1103443448/',
 'https://www.cars24.com/buy-used-hyundai-creta-2015-cars-new-delhi-1012990640/',
 'https://www.cars24.com/buy-used-tata-tiago-2017-cars-noida-1009425366/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-gurgaon-1003632801/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2015-cars-new-delhi-1483065041/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-noida-1054438867/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-faridabad-1002958444/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2014-cars-new-delhi-1008971969/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-noida-1007154809/',
 'https://www.cars24.com/buy-used-renault-duster-2013-cars-gurgaon-1010446629/',
 'https://www.cars24.com/buy-used-renault-duster-2013-cars-new-delhi-1051907761/',
 'https://www.cars24.com/buy-used-maruti-dzire-2017-cars-new-delhi-1006781269/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2014-cars-new-delhi-1006564907/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2014-cars-faridabad-1000710624/',
 'https://www.cars24.com/buy-used-mahindra-xuv500-2013-cars-faridabad-1001349808/',
 'https://www.cars24.com/buy-used-mg-hector-2020-cars-new-delhi-1153357165/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-new-delhi-1054357144/',
 'https://www.cars24.com/buy-used-hyundai-grand-i10-2014-cars-gurgaon-1100544820/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-gurgaon-1007118666/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-new-delhi-1008474809/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-new-delhi-1001538168/',
 'https://www.cars24.com/buy-used-hyundai-elite-i20-2014-cars-new-delhi-1009988906/',
 'https://www.cars24.com/buy-used-toyota-innova-2014-cars-new-delhi-1009072429/',
 'https://www.cars24.com/buy-used-ford-ecosport-2014-cars-new-delhi-1006335661/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-gurgaon-1013645261/',
 'https://www.cars24.com/buy-used-ford-ecosport-2013-cars-new-delhi-1124983441/',
 'https://www.cars24.com/buy-used-maruti-baleno-2016-cars-gurgaon-1010932661/']

In [8]:
carbrand = []
yearofmake = []
price = []
kilometersdriven = []
transmission = []
fueltype = []
owner = []


for link in urls:                 
    driver.get(link)
    time.sleep(2)
    
    try:                    
        cbrand =driver.find_element_by_xpath("//h2[@class='_2geSF']")
        carbrand.append(cbrand.text.split(" ")[1])
    except NoSuchElementException:
        carbrand.append('No details available')
        
    try:                    
        year =driver.find_element_by_xpath("//h2[@class='_2geSF']")
        yearofmake.append(year.text.split(" ")[0])
    except NoSuchElementException:
        yearofmake.append('No details available')

    try:                    
        prce =driver.find_element_by_xpath("//div[@class='text-right g-hPT']/strong")
        price.append(prce.text.strip("Fixed Price\n"))
    except NoSuchElementException:
        price.append('No details available')        

    try:                    
        kmd =driver.find_element_by_xpath("//ul[@class='_2KO13']/li[3]/strong")
        kilometersdriven.append(kmd.text)
    except NoSuchElementException:
        kilometersdriven.append('No details available')

    try:                    
        trans =driver.find_element_by_xpath("//ul[@class='_2KO13']/li[6]/strong")
        transmission.append(trans.text)
    except NoSuchElementException:
        transmission.append('No details available')        
        
    try:                    
        ftype =driver.find_element_by_xpath("//ul[@class='_2KO13']/li[4]/strong")
        fueltype.append(ftype.text)
    except NoSuchElementException:
        fueltype.append('No details available')

    try:                    
        own =driver.find_element_by_xpath("//ul[@class='_2KO13']/li[2]/strong")
        owner.append(own.text)
    except NoSuchElementException:
        owner.append('No details available')        
        
        
        
usercarlist = pd.DataFrame()
usercarlist['carbrandname'] = carbrand
usercarlist['yearofthemake'] = yearofmake
usercarlist['price'] = price
usercarlist['kilometersdriven'] = kilometersdriven
usercarlist['transmission'] = transmission
usercarlist['fueltype'] = fueltype
usercarlist['owner'] = owner
usercarlist

,carbrandname,yearofthemake,price,kilometersdriven,transmission,fueltype,owner
0,Maruti,2013,"₹3,03,099","49,944 km",MANUAL,Diesel,2nd Owner
1,Toyota,2011,"₹3,35,499","85,707 km",MANUAL,Petrol,1st Owner
2,Maruti,2009,"₹2,04,199","38,160 km",MANUAL,Petrol,1st Owner
3,Maruti,2009,"₹2,07,799","44,191 km",MANUAL,Petrol,1st Owner
4,Volkswagen,2014,"₹4,46,899","62,625 km",MANUAL,Petrol,1st Owner
...,...,...,...,...,...,...,...
175,Toyota,2014,"₹9,96,799","69,958 km",MANUAL,Diesel,1st Owner
176,Ford,2014,"₹4,66,899","78,005 km",MANUAL,Diesel,1st Owner
177,Maruti,2016,"₹5,23,999","72,334 km",MANUAL,Petrol,1st Owner
178,Ford,2013,"₹3,89,699","80,946 km",MANUAL,Diesel,2nd Owner
179,Maruti,2016,"₹5,12,999","87,113 km",MANUAL,Petrol,1st Owner

In [9]:
usercarlist.to_csv("usercarlist.csv")